const openBtn=document.getElementById('openInvite');const opening=document.getElementById('opening');const fx=document.getElementById('fx');const ctx=fx.getContext('2d');let W,H;function resize(){W=fx.width=innerWidth;H=fx.height=innerHeight}resize();addEventListener('resize',resize);function burst(x=W/2,y=H/2,n=80){const p=[];for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=2+Math.random()*7;p.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-2,r:2+Math.random()*4,l:70+Math.random()*40,c:Math.random()>.25?'#ffe7a6':'#d8b45f'})}let t=0;function draw(){ctx.clearRect(0,0,W,H);p.forEach(o=>{o.x+=o.vx;o.y+=o.vy;o.vy+=.08;o.l--;ctx.globalAlpha=Math.max(o.l/90,0);ctx.fillStyle=o.c;ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,7);ctx.fill()});ctx.globalAlpha=1;t++;if(t<120)requestAnimationFrame(draw);else ctx.clearRect(0,0,W,H)}draw()}openBtn?.addEventListener('click',()=>{opening.classList.add('open');burst(W/2,H*.42,120);sparkleSound();setTimeout(()=>opening.classList.add('hide'),1350)});document.getElementById('celebrate')?.addEventListener('click',()=>{sparkleSound();for(let i=0;i<5;i++)setTimeout(()=>burst(Math.random()*W,H*(.15+Math.random()*.45),70),i*260)});const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));function toAr(n){return String(n).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[d])}function pad(n){return toAr(String(n).padStart(2,'0'))}function tick(){document.querySelectorAll('.count-card').forEach(card=>{const target=new Date(card.dataset.target).getTime();let diff=Math.max(target-Date.now(),0);const d=Math.floor(diff/86400000);diff%=86400000;const h=Math.floor(diff/3600000);diff%=3600000;const m=Math.floor(diff/60000);const s=Math.floor((diff%60000)/1000);card.querySelector('[data-days]').textContent=pad(d);card.querySelector('[data-hours]').textContent=pad(h);card.querySelector('[data-mins]').textContent=pad(m);card.querySelector('[data-secs]').textContent=pad(s)})}tick();setInterval(tick,1000);

// Soft built-in wedding music using Web Audio API (no external audio file needed)
const musicBtn=document.getElementById('musicToggle');let audioCtx=null,master=null,musicOn=false,musicTimer=null,step=0;
const melody=[0,4,7,11,7,4,2,5,9,12,9,5,0,4,7,14];
function makeAudio(){if(audioCtx)return;audioCtx=new (window.AudioContext||window.webkitAudioContext)();master=audioCtx.createGain();master.gain.value=0;master.connect(audioCtx.destination)}
function midi(n){return 261.63*Math.pow(2,n/12)}
function tone(freq,time,dur,type='sine',gain=.08){const o=audioCtx.createOscillator();const g=audioCtx.createGain();o.type=type;o.frequency.value=freq;o.connect(g);g.connect(master);g.gain.setValueAtTime(0,time);g.gain.linearRampToValueAtTime(gain,time+.04);g.gain.exponentialRampToValueAtTime(.0001,time+dur);o.start(time);o.stop(time+dur+.05)}
function playPattern(){if(!musicOn||!audioCtx)return;const now=audioCtx.currentTime;const note=melody[step%melody.length];tone(midi(note),now,.75,'sine',.055);tone(midi(note-12),now,.9,'triangle',.035);if(step%4===0)tone(midi(-24),now,1.2,'sine',.04);step++;musicTimer=setTimeout(playPattern,720)}
async function toggleMusic(){makeAudio();if(audioCtx.state==='suspended')await audioCtx.resume();musicOn=!musicOn;musicBtn.classList.toggle('playing',musicOn);musicBtn.textContent=musicOn?'Ⅱ':'♪';if(musicOn){master.gain.cancelScheduledValues(audioCtx.currentTime);master.gain.setValueAtTime(master.gain.value,audioCtx.currentTime);master.gain.linearRampToValueAtTime(.28,audioCtx.currentTime+1.6);playPattern()}else{clearTimeout(musicTimer);master.gain.cancelScheduledValues(audioCtx.currentTime);master.gain.setValueAtTime(master.gain.value,audioCtx.currentTime);master.gain.linearRampToValueAtTime(0,audioCtx.currentTime+.8)}}
musicBtn?.addEventListener('click',toggleMusic);
function sparkleSound(){if(!audioCtx||!musicOn)return;const now=audioCtx.currentTime;tone(880,now,.22,'sine',.04);tone(1320,now+.06,.18,'sine',.03)}
